//! Apache and w3id.org.
//!
//! `.htaccess` in the `ids/<id>/` style w3id expects, which means no
//! hard-coded `/def` prefix and no assumption about where the file is mounted.
//!
//! Apache matches `Accept` with a regular expression and cannot rank
//! q-values, so `text/turtle;q=0.1, text/html` is indistinguishable from
//! `text/turtle, text/html;q=0.1`. The rules run from the most specific
//! request to the least, which misreads the fewest real requests.
//!
//! Apache appears in two quite different deployments and the rules for them
//! are not the same. As a redirect host in front of somewhere else, w3id
//! being the case this style is named for, every representation including the
//! page is a 303 to the document host. Serving the site itself, a 303 from a
//! term to its own page is a request for that same URL and therefore an
//! infinite redirect, so the page must be rewritten internally and only the
//! other representations redirected. The two are told apart by comparing the
//! origin a term is named at with the origin its documents are served from.
//!
//! Two things a naive rule set gets wrong, and which cost a working site.
//! A pattern of `([^/?#]+)` matches `Format.ttl` as readily as `Format`, so a
//! request for a sibling is rewritten to `Format.ttl.ttl`. And it matches
//! `shapes` in `/ontology/shapes/`, whose target is `/ontology/shapes`, which
//! matches again: an infinite redirect. Both are avoided by matching the
//! terms the namespace actually publishes, which is what `resolver_type:
//! strict` means, and by excluding reserved segments where the term list is
//! too large to inline.

use super::{format_alias, term_representations};
use crate::render::manifest::{Manifest, NamespaceEntry};
use std::fmt::Write;

/// Above this many terms an alternation of every name makes the file
/// unreadable and slow, so the rules fall back to excluding what is known not
/// to be a term. The degradation is written into the file.
const INLINE_TERM_LIMIT: usize = 300;

pub fn emit(manifest: &Manifest) -> Vec<(String, String)> {
    vec![(".htaccess".to_owned(), htaccess(manifest))]
}

fn escape(value: &str) -> String {
    value
        .chars()
        .map(|c| match c {
            '.' | '+' | '*' | '?' | '(' | ')' | '[' | ']' | '{' | '}' | '^' | '$' | '|' | '\\' => {
                format!("\\{c}")
            }
            other => other.to_string(),
        })
        .collect()
}

/// The regular expression that matches exactly the local names this namespace
/// resolves, and nothing else.
fn local_pattern(ns: &NamespaceEntry) -> String {
    if !ns.terms.is_empty() && ns.terms.len() <= INLINE_TERM_LIMIT {
        let names: Vec<String> = ns.terms.iter().map(|t| escape(t)).collect();
        return format!("({})", names.join("|"));
    }
    // Too many to list: exclude the segments that are known not to be terms,
    // and anything carrying an extension, which is a sibling being asked for
    // by name.
    let mut excluded: Vec<String> = ns.reserved.iter().map(|r| escape(r)).collect();
    for version in &ns.versions {
        excluded.push(escape(&version.segment));
    }
    excluded.sort();
    excluded.dedup();
    let not_reserved = if excluded.is_empty() {
        String::new()
    } else {
        format!("(?!(?:{})(?:/|$))", excluded.join("|"))
    };
    format!("{not_reserved}([^/?#.]+)")
}

/// The origin of an absolute URL, for telling a redirect host from a serving
/// host.
fn origin(url: &str) -> &str {
    let rest = url.split_once("//").map(|(_, r)| r).unwrap_or(url);
    match rest.find('/') {
        Some(i) => &url[..url.len() - (rest.len() - i)],
        None => url,
    }
}

/// Whether this Apache is in front of somewhere else rather than serving the
/// files itself.
fn is_redirect_host(ns: &NamespaceEntry) -> bool {
    origin(&ns.iri_base) != origin(&ns.doc_base)
}

fn htaccess(manifest: &Manifest) -> String {
    let redirect_host = manifest.namespaces.iter().any(is_redirect_host);
    let mut s = String::new();
    let _ = writeln!(
        s,
        "# Generated by iyo from manifest.json. Do not edit; rebuild instead.\n\
         #\n\
         # Apache matches Accept with a regular expression and cannot rank q-values,\n\
         # so a request naming several types may be answered with any of them. Rules\n\
         # run from the most specific request to the least.\n\
         #\n\
         # Options -MultiViews is required: MultiViews would answer /Format with\n\
         # Format.ttl on its own terms and never reach these rules."
    );
    if redirect_host {
        let _ = writeln!(
            s,
            "#\n\
             # This host redirects to another origin, so every representation is a 303.\n\
             # Place this as ids/<id>/.htaccess in a w3id.org checkout."
        );
    } else {
        let _ = writeln!(
            s,
            "#\n\
             # This host serves the files, so a page is rewritten internally and only the\n\
             # other representations are redirected. Redirecting a term to its own page\n\
             # would be a redirect to the request that was just made. Place this at the\n\
             # document root."
        );
    }
    let _ = writeln!(s, "\nOptions -MultiViews");
    let _ = writeln!(s, "RewriteEngine On\n");
    if !redirect_host {
        let _ = writeln!(
            s,
            "# A request for a file that exists is never a term to be negotiated."
        );
        let _ = writeln!(s, "RewriteCond %{{REQUEST_FILENAME}} -f");
        let _ = writeln!(s, "RewriteRule ^ - [L]\n");
        let _ = writeln!(s, "Header always set Vary Accept");
        let _ = writeln!(s, "Header always set Access-Control-Allow-Origin \"*\"\n");
    }

    for ns in &manifest.namespaces {
        let prefix = escape(
            &ns.resolver_prefix
                .clone()
                .unwrap_or_else(|| ns.mount.trim_matches('/').to_owned()),
        );
        let redirecting = is_redirect_host(ns);
        // A redirect host sends the client to the document origin; a serving
        // host rewrites to a path under its own root.
        let base = if redirecting {
            ns.doc_base.trim_end_matches('/').to_owned()
        } else {
            ns.mount.trim_end_matches('/').to_owned()
        };
        let _ = writeln!(s, "# --- {} ---", ns.iri_base);
        if ns.terms.len() > INLINE_TERM_LIMIT {
            let _ = writeln!(
                s,
                "# {} terms: too many to list, so these rules match anything that is not a\n\
                 # reserved segment and carries no extension, rather than the exact term list.",
                ns.terms.len()
            );
        }

        for version in &ns.versions {
            // Serving the files, this rule only adds the missing slash: a
            // pattern of `/?$` matches the slashed form too, whose target is
            // itself, which is an infinite redirect. Redirecting onwards, the
            // target is another origin and both forms are safe to match.
            let tail = if redirecting { "/?$" } else { "$" };
            let _ = writeln!(
                s,
                "RewriteRule ^{prefix}/{}{tail} {base}/{}/ [R=302,L]",
                escape(&version.segment),
                version.segment
            );
        }

        for local in &ns.dir_terms {
            emit_term_rules(
                &mut s,
                ns,
                &prefix,
                &base,
                &escape(local),
                local,
                true,
                redirecting,
            );
        }

        // A namespace that publishes no terms resolves no terms. Falling
        // through to the general pattern would make it match every name,
        // which is how a shapes document came to answer for
        // `/vocab/shapes/anything.ttl`.
        if ns.terms.is_empty() && ns.resolver_type == "strict" {
            let _ = writeln!(s, "# no terms: nothing under this mount is negotiated");
            if redirecting {
                let _ = writeln!(
                    s,
                    "RewriteRule ^{prefix}/?$ {base}/ [R={},L]\n",
                    ns.status_code
                );
            } else {
                let _ = writeln!(s, "RewriteRule ^{prefix}/?$ {base}/index.html [L]\n");
            }
            continue;
        }

        let pattern = local_pattern(ns);
        emit_term_rules(
            &mut s,
            ns,
            &prefix,
            &base,
            &pattern,
            "$1",
            ns.layout == "dir",
            redirecting,
        );

        if redirecting {
            let _ = writeln!(
                s,
                "RewriteRule ^{prefix}/?$ {base}/ [R={},L]\n",
                ns.status_code
            );
        } else {
            let _ = writeln!(s, "RewriteRule ^{prefix}/?$ {base}/index.html [L]\n");
        }
    }
    s
}

/// One term's worth of rules: every non-default representation by `Accept` or
/// by `?format=`, then the page for everything else.
#[allow(clippy::too_many_arguments)]
fn emit_term_rules(
    s: &mut String,
    ns: &NamespaceEntry,
    prefix: &str,
    base: &str,
    pattern: &str,
    target_name: &str,
    dir: bool,
    redirecting: bool,
) {
    for rep in term_representations(ns) {
        if rep.media_type == ns.default_type {
            continue;
        }
        let suffix = rep.suffix.clone().unwrap_or_default();
        let target = if dir {
            format!("{base}/{target_name}/index{suffix}")
        } else {
            format!("{base}/{target_name}{suffix}")
        };
        let _ = writeln!(
            s,
            "RewriteCond %{{HTTP_ACCEPT}} {} [NC]",
            escape(&rep.media_type)
        );
        let _ = writeln!(
            s,
            "RewriteRule ^{prefix}/{pattern}/?$ {target} [R={},L]",
            ns.status_code
        );
        let alias = format_alias(&rep.media_type);
        if !alias.is_empty() {
            let _ = writeln!(s, "RewriteCond %{{QUERY_STRING}} (^|&)format={alias}(&|$)");
            let _ = writeln!(
                s,
                "RewriteRule ^{prefix}/{pattern}/?$ {target} [R={},L]",
                ns.status_code
            );
        }
    }
    // The page. A redirect host sends the client on; a serving host answers
    // with the file, because redirecting to the URL just requested is a loop.
    if redirecting {
        let html = if dir {
            format!("{base}/{target_name}/")
        } else {
            format!("{base}/{target_name}")
        };
        let _ = writeln!(
            s,
            "RewriteRule ^{prefix}/{pattern}/?$ {html} [R={},L]",
            ns.status_code
        );
    } else {
        let file = if dir {
            format!("{base}/{target_name}/index.html")
        } else {
            format!("{base}/{target_name}.html")
        };
        let _ = writeln!(s, "RewriteRule ^{prefix}/{pattern}/?$ {file} [L]");
    }
}
