//! Cloudflare Workers static assets.
//!
//! The only host in the table that loses nothing, and the only one that needs
//! code. `_headers` cannot carry per-term `Link` headers because Cloudflare
//! allows 100 rules and 2,000 characters a line, so the Worker sets them and
//! `_headers` carries only what applies to whole classes of file.
//!
//! The Worker embeds its routing table rather than fetching `manifest.json`
//! at run time. A fetch would be a subrequest on every cold start for data
//! that cannot change without a redeploy, and it would make the Worker's
//! behaviour depend on a file a later deploy might not have.

use super::{format_alias, is_rdf, term_representations};
use crate::render::manifest::Manifest;
use serde_json::{Value, json};
use std::collections::BTreeSet;
use std::fmt::Write;

/// A wrangler compatibility date old enough to be valid and recent enough to
/// have modern defaults. Not read from the clock: a build must be
/// reproducible, and a generated file that changes because a day passed is
/// not reproducible.
const COMPATIBILITY_DATE: &str = "2024-11-01";

pub fn emit(manifest: &Manifest) -> Vec<(String, String)> {
    vec![
        ("worker.js".to_owned(), worker(manifest)),
        ("_headers".to_owned(), headers(manifest)),
        ("_redirects".to_owned(), redirects(manifest)),
        ("wrangler.toml".to_owned(), wrangler(manifest)),
    ]
}

/// The routing table the Worker needs, and nothing else.
fn table(manifest: &Manifest) -> Value {
    let namespaces: Vec<Value> = manifest
        .namespaces
        .iter()
        .map(|ns| {
            let reps: Vec<Value> = term_representations(ns)
                .iter()
                .map(|r| {
                    json!({
                        "type": r.media_type,
                        "suffix": r.suffix.clone().unwrap_or_default(),
                        "alias": format_alias(&r.media_type),
                        "rdf": is_rdf(&r.media_type),
                    })
                })
                .collect();
            json!({
                "mount": ns.mount,
                "iri": ns.iri_base,
                "dir": ns.layout == "dir",
                "dirTerms": ns.dir_terms,
                "strict": ns.resolver_type == "strict",
                "default": ns.default_type,
                "status": ns.status_code,
                "cache": ns.cache_control,
                "snapshotCache": ns.snapshot_cache_control,
                "snapshots": ns.versions.iter()
                    .map(|v| json!({ "segment": v.segment, "url": v.url }))
                    .collect::<Vec<_>>(),
                "llms": ns.llms_txt,
                "reps": reps,
                "terms": ns.terms,
            })
        })
        .collect();
    json!({ "root": manifest.site_root, "namespaces": namespaces })
}

fn worker(manifest: &Manifest) -> String {
    let table = serde_json::to_string(&table(manifest)).unwrap_or_else(|_| "{}".to_owned());
    format!(
        r#"// Generated by iyo from manifest.json. Do not edit; rebuild instead.
//
// Content negotiation for a static vocabulary site, following
// the negotiation rules in docs/output-convention.md. No dependencies.
//
// The rules that are easy to get wrong, and are therefore spelled out:
//  - Accept is parsed with q-values. Matching it with a regular expression
//    mis-orders preferences, which is how "text/turtle;q=0.1, text/html" ends
//    up serving Turtle to a browser.
//  - An explicit media type always beats a wildcard, whatever its q-value, so
//    a browser sending `*/*` gets HTML rather than whichever type happens to
//    be declared first.
//  - A client that asked only for RDF types we do not have still gets RDF,
//    not HTML, because it plainly wanted data.
//  - Nothing 406s by default. A 406 is a worse answer than a usable one.

const TABLE = {table};

const ALIASES = {{ html: "text/html", md: "text/markdown", ttl: "text/turtle",
  jsonld: "application/ld+json", rdf: "application/rdf+xml",
  nt: "application/n-triples", json: "application/ld+json" }};

// RFC 9110 Accept, as a list of {{ type, q }} sorted by q descending, stable
// within a q so that the client's own order survives.
function parseAccept(header) {{
  if (!header) return [];
  return header
    .split(",")
    .map((part, index) => {{
      const [type, ...params] = part.trim().split(";");
      let q = 1;
      for (const p of params) {{
        const [k, v] = p.split("=").map((s) => (s || "").trim());
        if (k === "q") {{
          const parsed = parseFloat(v);
          if (!Number.isNaN(parsed)) q = parsed;
        }}
      }}
      return {{ type: type.trim().toLowerCase(), q, index }};
    }})
    .filter((a) => a.type && a.q > 0)
    .sort((a, b) => b.q - a.q || a.index - b.index);
}}

function select(ns, accept, override) {{
  if (override) {{
    const wanted = ALIASES[override] || override;
    const hit = ns.reps.find((r) => r.type === wanted);
    if (hit) return hit;
  }}
  const parsed = parseAccept(accept);
  // Explicit types first, in the client's order of preference.
  for (const a of parsed) {{
    if (a.type === "*/*" || a.type.endsWith("/*")) continue;
    const hit = ns.reps.find((r) => r.type === a.type);
    if (hit) return hit;
  }}
  // A wildcard means "anything", and the default is what we consider best.
  const wildcard = parsed.find((a) => a.type === "*/*" || a.type.endsWith("/*"));
  if (wildcard) {{
    if (wildcard.type === "text/*") {{
      const text = ns.reps.find((r) => r.type.startsWith("text/") && r.type === ns.default)
        || ns.reps.find((r) => r.type.startsWith("text/"));
      if (text) return text;
    }}
    return ns.reps.find((r) => r.type === ns.default) || ns.reps[0];
  }}
  // Asked for data we do not have: give data, not a web page.
  if (parsed.length && parsed.every((a) => !ns.reps.some((r) => r.type === a.type))) {{
    const askedForRdf = parsed.some((a) => a.type.includes("rdf") || a.type.includes("turtle")
      || a.type.includes("ld+json") || a.type.includes("n-triples") || a.type.includes("trig"));
    if (askedForRdf) {{
      const rdf = ns.reps.find((r) => r.rdf);
      if (rdf) return rdf;
    }}
  }}
  return ns.reps.find((r) => r.type === ns.default) || ns.reps[0];
}}

function isDir(ns, local) {{
  return ns.dir || (ns.dirTerms || []).indexOf(local) !== -1;
}}

function filePath(ns, local, rep) {{
  if (isDir(ns, local)) {{
    return ns.mount + local + "/index" + (rep.suffix || ".html");
  }}
  return ns.mount + local + (rep.suffix || ".html");
}}

function publicUrl(ns, local, rep) {{
  if (isDir(ns, local)) {{
    return rep.suffix ? ns.mount + local + "/index" + rep.suffix : ns.mount + local + "/";
  }}
  return ns.mount + local + rep.suffix;
}}

// A relative reference from one absolute site path to another, as RFC 3986
// resolves it against the request URI.
function relativeTo(from, to) {{
  const split = (p) => {{
    const cut = p.lastIndexOf("/");
    const dir = cut === -1 ? "" : p.slice(0, cut);
    return [dir.split("/").filter(Boolean), cut === -1 ? p : p.slice(cut + 1)];
  }};
  const [fromDirs] = split(from);
  const [toDirs, toFile] = split(to);
  let shared = 0;
  while (shared < fromDirs.length && shared < toDirs.length
    && fromDirs[shared] === toDirs[shared]) shared++;
  const out = "../".repeat(fromDirs.length - shared)
    + toDirs.slice(shared).map((d) => d + "/").join("") + toFile;
  return out === "" ? "./" : out;
}}

// `canonical` and `cite-as` name the resource and are absolute wherever they
// are read, so canonical is the origin the manifest declares and not the one
// this request happened to arrive on. `alternate` and `describedby` name
// something the client is expected to fetch, so they are relative references
// and resolve against the request URI.
function linkHeader(ns, local, chosen, origin) {{
  const root = (TABLE.root || origin).replace(/\/$/, "");
  const from = requestPath(ns, local);
  const canonical = root + publicUrl(ns, local, ns.reps.find((r) => r.type === ns.default) || ns.reps[0]);
  const parts = [`<${{canonical}}>; rel="canonical"`];
  parts.push(`<${{ns.iri + local}}>; rel="cite-as"`);
  for (const rep of ns.reps) {{
    if (rep === chosen) continue;
    parts.push(`<${{relativeTo(from, publicUrl(ns, local, rep))}}>; rel="alternate"; type="${{rep.type}}"`);
  }}
  const llms = ns.llms.startsWith(root) ? ns.llms.slice(root.length) : ns.llms;
  parts.push(`<${{relativeTo(from, llms)}}>; rel="describedby"; type="text/plain"`);
  return parts.join(", ");
}}

function requestPath(ns, local) {{
  return isDir(ns, local) ? ns.mount + local + "/" : ns.mount + local;
}}

export default {{
  async fetch(request, env) {{
    const url = new URL(request.url);
    const path = decodeURIComponent(url.pathname);

    // The longest matching mount wins: /vocabulary/category/ before
    // /vocabulary/, or every scheme would resolve as a term of the parent.
    let ns = null;
    for (const candidate of TABLE.namespaces) {{
      if (path.startsWith(candidate.mount)
        && (!ns || candidate.mount.length > ns.mount.length)) ns = candidate;
    }}
    if (!ns) return env.ASSETS.fetch(request);

    let local = path.slice(ns.mount.length);
    if (local.endsWith("/")) local = local.slice(0, -1);

    // A release is published under a segment of its own, and its terms
    // negotiate exactly as the newest ones do, so they resolve against the
    // same namespace moved onto that segment.
    const cut = local.indexOf("/");
    if (cut !== -1) {{
      const snap = (ns.snapshots || []).find((s) => s.segment === local.slice(0, cut));
      if (!snap) return withCache(ns, path, await env.ASSETS.fetch(request));
      ns = snapshotEntry(ns, snap);
      local = local.slice(cut + 1);
      if (local.endsWith("/")) local = local.slice(0, -1);
    }}
    // Anything with a path separator still left is a nested document, and is
    // served as it is asked for.
    if (local.indexOf("/") !== -1 || local === "") return withCache(ns, path, await env.ASSETS.fetch(request));
    // A request that already names a representation is not a negotiation.
    if (ns.reps.some((r) => r.suffix && local.endsWith(r.suffix))) {{
      return withCache(ns, path, await env.ASSETS.fetch(request));
    }}
    if (ns.strict && ns.terms.indexOf(local) === -1) {{
      return withCache(ns, path, await env.ASSETS.fetch(request));
    }}

    const override = url.searchParams.get("format")
      || url.searchParams.get("_mediatype")
      || url.searchParams.get("_profile");
    const chosen = select(ns, request.headers.get("accept"), override);
    const link = linkHeader(ns, local, chosen, url.origin);

    if (chosen.type === ns.default) {{
      const asset = await env.ASSETS.fetch(new URL(filePath(ns, local, chosen), url.origin));
      const response = new Response(asset.body, asset);
      response.headers.set("Vary", "Accept");
      response.headers.set("Link", link);
      response.headers.set("Cache-Control", ns.cache);
      response.headers.set("Access-Control-Allow-Origin", "*");
      return response;
    }}

    // Redirecting to a representation-specific URL is the cache-safe choice
    // on a CDN that ignores Vary.
    return new Response(null, {{
      status: ns.status,
      headers: {{
        Location: publicUrl(ns, local, chosen),
        Vary: "Accept",
        Link: link,
        "Cache-Control": ns.cache,
        "Access-Control-Allow-Origin": "*",
      }},
    }});
  }},
}};

// The namespace as it exists inside one release: the same terms and the same
// layout, mounted under the version segment. A release is what you cite when
// you cite a release, so its documents are their own identity, and they never
// expire.
function snapshotEntry(ns, snap) {{
  return Object.assign({{}}, ns, {{
    mount: ns.mount + snap.segment + "/",
    iri: snap.url,
    // A release writes its own agent index, so describedby names that one and
    // not the parent's, which no longer lists the same terms.
    llms: snap.url + ns.llms.slice(ns.llms.lastIndexOf("/") + 1),
    cache: ns.snapshotCache,
    snapshots: [],
  }});
}}

// A release never changes, so it can be cached forever; latest changes with
// every release, so it cannot. Every one of a namespace's own files gets
// this -- not only a negotiated term page -- because that is what the cache
// values in the manifest mean: the output convention states
// them as a rule about paths ("Snapshot paths carry ... latest carries
// ..."), not about negotiated responses specifically. A sibling asked for
// by name and a namespace's own document are both that namespace's own
// files, and open CORS plus Vary: Accept apply the same way. Not on a 404:
// nothing here is this namespace's file.
function withCache(ns, path, response) {{
  if (response.status === 404) return response;
  const rest = path.slice(ns.mount.length);
  const segment = rest.split("/")[0];
  const inSnapshot = (ns.snapshots || []).some((s) => s.segment === segment);
  const copy = new Response(response.body, response);
  copy.headers.set("Cache-Control", inSnapshot ? ns.snapshotCache : ns.cache);
  copy.headers.set("Vary", "Accept");
  copy.headers.set("Access-Control-Allow-Origin", "*");
  return copy;
}}
"#
    )
}

fn headers(manifest: &Manifest) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "# Generated by iyo from manifest.json. Do not edit; rebuild instead.\n\
         #\n\
         # Cloudflare allows 100 rules and 2,000 characters a line, so per-term\n\
         # Link headers are set by worker.js and this file carries only what\n\
         # applies to a whole class of file.\n"
    );
    let _ = writeln!(s, "/*");
    let _ = writeln!(s, "  Access-Control-Allow-Origin: *");
    let _ = writeln!(s, "  X-Content-Type-Options: nosniff");
    // Tell an agent crawler what is allowed without waiting for a robots
    // convention that does not exist yet.
    let _ = writeln!(s, "  Content-Signal: search=yes, ai-train=yes\n");

    // Media types, so that a `.ttl` is not served as text/plain.
    let mut seen: BTreeSet<String> = BTreeSet::new();
    for ns in &manifest.namespaces {
        for rep in &ns.representations {
            let Some(suffix) = rep.suffix.as_deref().filter(|s| !s.is_empty()) else {
                continue;
            };
            if !seen.insert(rep.media_type.clone()) {
                continue;
            }
            let charset = if rep.media_type.starts_with("text/") {
                "; charset=utf-8"
            } else {
                ""
            };
            let _ = writeln!(s, "/*{suffix}");
            let _ = writeln!(s, "  Content-Type: {}{charset}", rep.media_type);
            let _ = writeln!(s, "  Vary: Accept");
            let _ = writeln!(s, "  Access-Control-Allow-Origin: *\n");
        }
    }

    // Releases are immutable; everything else revalidates.
    for ns in &manifest.namespaces {
        for version in &ns.versions {
            let _ = writeln!(s, "{}{}/*", ns.mount, version.segment);
            let _ = writeln!(s, "  Cache-Control: {}", ns.snapshot_cache_control);
            let _ = writeln!(s, "  Access-Control-Allow-Origin: *\n");
        }
    }
    for ns in &manifest.namespaces {
        let _ = writeln!(s, "{}*", ns.mount);
        let _ = writeln!(s, "  Cache-Control: {}\n", ns.cache_control);
    }
    s
}

fn redirects(manifest: &Manifest) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "# Generated by iyo from manifest.json. Do not edit; rebuild instead.\n\
         #\n\
         # Unconditional redirects only: legacy paths that must keep working.\n\
         # Negotiation is worker.js's job, because a redirect cannot read Accept.\n\
         # Cloudflare applies the first match, so order is significant."
    );
    let mut rules = 0usize;
    for ns in &manifest.namespaces {
        // A release IRI written without its trailing slash still has to land
        // on the release rather than on a 404.
        for version in &ns.versions {
            let _ = writeln!(
                s,
                "{}{} {}{}/ 301",
                ns.mount, version.segment, ns.mount, version.segment
            );
            rules += 1;
        }
    }
    if rules == 0 {
        let _ = writeln!(s, "# (none for this release)");
    }
    s
}

fn wrangler(manifest: &Manifest) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "# Generated by iyo from manifest.json. Merge into your own wrangler.toml.\n\
         #\n\
         # `run_worker_first` is scoped to the mounts and excludes the sibling\n\
         # extensions, so a request for a file that exists is served by the asset\n\
         # layer and never wakes the Worker."
    );
    let name = manifest
        .namespaces
        .first()
        .map(|n| n.id.clone())
        .unwrap_or_else(|| "vocabulary".to_owned());
    let _ = writeln!(s, "\nname = \"{name}\"");
    let _ = writeln!(s, "main = \"worker.js\"");
    let _ = writeln!(
        s,
        "# Raise this when you next review the Worker; it is fixed so that two\n\
         # builds of the same release produce the same file."
    );
    let _ = writeln!(s, "compatibility_date = \"{COMPATIBILITY_DATE}\"");
    let _ = writeln!(s, "\n[assets]");
    let _ = writeln!(s, "directory = \"./dist\"");
    let _ = writeln!(s, "binding = \"ASSETS\"");
    let _ = writeln!(s, "not_found_handling = \"404-page\"");

    let mut patterns: Vec<String> = Vec::new();
    for ns in &manifest.namespaces {
        patterns.push(format!("\"{}*\"", ns.mount));
    }
    let mut suffixes: BTreeSet<&str> = BTreeSet::new();
    for ns in &manifest.namespaces {
        for rep in &ns.representations {
            if let Some(suffix) = rep.suffix.as_deref().filter(|s| !s.is_empty()) {
                suffixes.insert(suffix);
            }
        }
    }
    for ns in &manifest.namespaces {
        for suffix in &suffixes {
            patterns.push(format!("\"!{}*{suffix}\"", ns.mount));
        }
    }
    let _ = writeln!(s, "run_worker_first = [\n  {}\n]", patterns.join(",\n  "));
    s
}
